### ISSUE TITLE
MAX22216 unused register, wrong register and field names

### ISSUE THREAD

**Issue by jonas-ott** [analogdevicesinc/TMC-API#58]
In the MAX22216 register definitions `MAX22216_I_DC_0`  is defined as 0x46 (and the same for the other channels) however according to the datasheet 0x46 is not used.

Also, in comparison to the data sheet, some names for registers and fields are different.
Here are the differences in register names:

_name in header : name in data sheet_
DEMAG_VOLTAGE : DC_H2L
ADC_VM_MEASUREMENT : VM_MONITOR
CFG_DC : CFG_IDC_THLD
I_ADC : I_MONITOR 
I_IND_AC : I_AC
R : RES 

And here are the fields with a wrong name:

_name in header : name in data sheet_
ADC_VM_RAW : VM_MONITOR
DELTA_PHI : F_AC_SCAN
U_AC : U_AC_SCAN

**Comment by trinamic-ASU** [comment]
Thanks for pointing that out. We have updated the registers and the fields.

**Comment by jonas-ott** [comment]
Thanks
